### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cs0x7f** [cs0x7f/cstimer#3]
- [x] more draw scramble options, e.g. megaminx
- [x] export times into csv/txt
- [x] truncates the third decimal?
- [x] Include metronome in Tools menu for look ahead training such as F2L
- [ ] Improve UI
- [x] Login by google account and use Google Drive to store data

**Comment by pr0jectile** [comment]
Just a quick suggestion...

- [ ]  Include metronome in Tools menu for look ahead training such as F2L

Let me know what you think.

I'm a graphic / web designer by the way, I can create a new skin for csTimer if you want me to. Just let me know :)

Thanks!

**Comment by cvaughn55** [comment]
I have a suggustion that you try to make the sire have a mobile version, and add PWA support for it so people can add it to their homescreen and use it offline
